### PR TITLE
Fixes #129 - Take a few stabs at preventing corrupted config.json

### LINKED ISSUE #129: ignoredDomains sometimes tranformed into array of empty objects
It's sometimes possible for `ignoredDomains` to end up as an array of empty objects, rather than strings. (`{}, {}, {}`....). A few weeks ago I tried to reproduce, but only saw it once. It just happened on the staging server.

### PR DESCRIPTION
**Pull request by miketaylr**
I did run into another instance of #130 while testing this PR, and the config didn't get corrupted. So it's at best circumstantial evidence that this PR doesn't make things worse. :)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,13 +1,16 @@
...
 const helpers = require("./helpers");
 const spreadsheet = require("./spreadsheet");
 const tranco = require("./tranco");
 
 const argv = process.argv.slice(2);
 
 const main = async () => {
-  const config = require("./config.json");
+  const config = JSON.parse(
+    await fs.promises.readFile("config.json", { encoding: "utf8" })
```
Comment (miketaylr) [inline index.js]: I decided to not use `fs.readFileSync` since we're already inside an async fn at this point. Might as well use the cool stuff, but I can change it to be consistent with helpers.js

File: tranco.js [hunk 2]
```diff
@@ -45,14 +45,12 @@ const removeIgnoredDomains = function(listFile) {
     // Modify the website list, if we have any ignoredDomains.
     if (IGNORED_DOMAINS.length) {
       if (!DOMAINS_REGEXP_CACHE.length) {
-        DOMAINS_REGEXP_CACHE = IGNORED_DOMAINS.map((value, index) => {
+        DOMAINS_REGEXP_CACHE = IGNORED_DOMAINS.map(value => {
```
Comment (miketaylr) [inline tranco.js]: I don't see how `IGNORED_DOMAINS` being mutated into an array of regular expressions would affect the config, but if you do call `JSON.stringify` on a regexp, it will stringify to an empty object...
