### PR TITLE
Fixes #77 - Filter out bugs reported by SoftVision

### LINKED ISSUE #77: Filter out SoftVision filed bugs
The idea is that this change will reflect a more organic measurement.

Curious to see if this changes the trends, but let's implement it and test. For consistency, we should probably include both Bugzilla and GitHub bugs.

(for now let's just scope it to SV, and ignore Mozilla-filed bugs)

### PR DESCRIPTION
**Pull request by miketaylr**

### CODE REVIEW

File: bugs.js [hunk 1]
```diff
@@ -6,8 +6,24 @@ const Octokit = require('@octokit/rest')
...
+    getBugzillaStatuses,
+    isMobileBugzilla,
+    isMobileWebCompat,
+    isNotSVBugzilla,
+    isNotSVWebCompat,
+} = require('./helpers');
 
-const searchConstraintQueryFragment = "&keywords_type=nowords&keywords=meta%2C%20&status_whiteboard_type=notregexp&status_whiteboard=sci%5C-exclude";
+// don't include results that:
+// * containt a meta keyword
```
Comment (miketaylr) [inline bugs.js]: cool typo, mike

File: bugs.js [hunk 2]
```diff
@@ -6,8 +6,24 @@ const Octokit = require('@octokit/rest')
     .plugin(require('@octokit/plugin-throttling'))
     .plugin(require('@octokit/plugin-retry'));
 const util = require('util')
+const {
```
Comment (miketaylr) [inline bugs.js]: Maybe this style of imports is annoying? We could also just do `const helpers = require('./helpers')` and prefix all usage by `helpers.foo()`.

Comment (miketaylr) [reply bugs.js]: (i don't really care either way)

File: bugs.js [hunk 3]
```diff
@@ -165,45 +103,22 @@ const getBugzilla = async (website, bugzillaKey, minDate, maxDate = new Date())
...
-    const openResults = await bugzillaRetry(openApiQuery);
-    const resolvedResults = await bugzillaRetry(resolvedApiQuery);
-    const openMobileResults = openResults.bugs.filter(isMobileBugzilla);
-    const resolvedMobileResults = resolvedResults.bugs.filter(isMobileBugzilla);
-    const results = openResults.bugs.concat(resolvedResults.bugs);
+    const openApiQuery = `https://bugzilla.mozilla.org/rest/bug?include_fields=id,summary,status,priority,product,component,creator${getBugzillaPriorities()}&bug_file_loc=${formatWebSiteForRegExp(website)}&bug_file_loc_type=regexp${getBugzillaStatuses()}&f1=OP&f3=creation_ts&o3=greaterthaneq${getBugzillaProducts()}&resolution=---&v3=${minDateQuery}&api_key=${bugzillaKey}${maxDateQueryFragment}${searchConstraintQueryFragment}`;
```
Comment (miketaylr) [inline bugs.js]: It's hard to see, but I'm just adding `,creator` to the `include_fields` here, same for `resolvedApiQuery`

File: bugs.js (hunk 2 above)
Comment (past) [reply bugs.js]: In general I'm in favor of consistency, but I don't really mind either.

File: helpers.js [hunk 4]
```diff
@@ -0,0 +1,134 @@
...
+function isMobileWebCompat(bug) {
+    const mobileLabels = ['browser-fenix', 'browser-firefox-mobile', 'browser-focus-geckoview', 'browser-geckoview'];
+    return bug.labels.some(label => mobileLabels.includes(label.name));
+}
+
+/**
+* Returns true if the webcompat.com bug was reported by one of our WebCompat SoftVision team members
+*/
+function isNotSVWebCompat(bug) {
+    const gitHubIDs = ['softvision-oana-arbuzov', 'softvision-sergiulogigan', 'cipriansv'];
```
Comment (past) [inline helpers.js]: We should really move most (all?) of the constants in this file to the configuration file, doubly so for these. Otherwise expanding or changing the team will require editing code. 

Maybe also make the function name and comments more generic, like `isNotFromQA`?

Comment (miketaylr) [reply helpers.js]: Great point. Thanks!
