### PR TITLE
Fixes #104 - Ignore severity-minor bugs from GitHub counts

### LINKED ISSUE #104: Exclude severity-minor bugs
These are effectively P5s, which we already ignore on Bugzilla.

### PR DESCRIPTION
**Pull request by miketaylr**
Will link to a run in a few.

### CODE REVIEW

File: bugs.js [hunk 1]
```diff
@@ -227,12 +227,14 @@ const getWebcompat = async (website, githubKey, minDate, maxDate, includeFenix)
         .filter(bug => includeFenix || !bug.labels.some(label => label.name.includes("browser-fenix")))
         // filter out any bugs with an sci-exclude label or filed by SoftVision
         .filter(bug => bug.labels.every(label => label.name !== "sci-exclude"))
+        .filter(bug => bug.labels.every(label => label.name !== "severity-minor"))
```
Comment (past) [inline bugs.js]: Optional nit: a single filter check should be faster, but I don't know if it would be perceptible. 

A more interesting question: shouldn't we make all these filter checks in the duplicate calculations, too? Could it be that sci-exclude, severity-minor, browser-fenix and isQA cause the duplicate count to balloon?

Comment (miketaylr) [reply bugs.js]: > shouldn't we make all these filter checks in the duplicate calculations, too?

Hm, yeah. Good point. Worth investigating. I'll merge here and file a follow up.
